import { minimalSdDbnDocument } from "./minimalSdDbn.js";

export { minimalSdDbnDocument } from "./minimalSdDbn.js";

export const onboardingSdDbnDocument = {
  "@type": "SD-DBN",
  version: "3.0",
  id: "doc-onboarding-evaluation-001",
  subject: "onboarding-evaluation",
  schema: {
    variables: [
      {
        id: "S_growth",
        kind: "situation",
        domain: ["false", "true"],
        text: "Hiring demand expands",
      },
      {
        id: "S_distributed_managers",
        kind: "situation",
        domain: ["false", "true"],
        text: "Managers are distributed",
      },
      {
        id: "X_progress_visibility",
        kind: "latent",
        role: "state",
        domain: ["absent", "present"],
        desired_values: ["present"],
        undesired_values: ["absent"],
        text: "Progress visibility is shared",
      },
      {
        id: "X_intervention_delay",
        kind: "latent",
        role: "obstacle",
        domain: ["absent", "present"],
        desired_values: ["absent"],
        undesired_values: ["present"],
        text: "Intervention is delayed",
      },
      {
        id: "X_action_metrics",
        kind: "latent",
        role: "means",
        domain: ["unfit", "fit"],
        desired_values: ["fit"],
        undesired_values: ["unfit"],
        text: "Action metrics reveal progress",
      },
      {
        id: "X_weekly_review",
        kind: "latent",
        role: "means",
        domain: ["unfit", "fit"],
        desired_values: ["fit"],
        undesired_values: ["unfit"],
        text: "Weekly review closes gaps",
      },
      {
        id: "X_stable_judgment",
        kind: "latent",
        role: "goal",
        domain: ["unmet", "met"],
        desired_values: ["met"],
        undesired_values: ["unmet"],
        text: "Stable onboarding judgment",
      },
      {
        id: "O_manager_variance",
        kind: "observation",
        domain: ["unobserved", "observed"],
        text: "Manager judgment differs",
      },
      {
        id: "O_gap_closed",
        kind: "observation",
        domain: ["unobserved", "observed"],
        text: "Review closes a candidate gap",
      },
    ],
    relations: [
      {
        id: "r_growth_visibility",
        type: "conditioning",
        scheme: "CONDITIONS",
        from: "S_growth",
        to: "X_progress_visibility",
        cpd: { direction: "decrease", strength: "moderate" },
      },
      {
        id: "r_manager_delay",
        type: "conditioning",
        scheme: "CONDITIONS",
        from: "S_distributed_managers",
        to: "X_intervention_delay",
        cpd: { direction: "increase", strength: "moderate" },
      },
      {
        id: "r_variance_visibility",
        type: "emission",
        scheme: "MANIFESTS_AS",
        from: "X_progress_visibility",
        to: "O_manager_variance",
        cpd: {
          "absent->observed": 0.82,
          "present->observed": 0.18,
        },
      },
      {
        id: "r_metrics_visibility",
        type: "inference",
        scheme: "RESOLVES",
        from: "X_action_metrics",
        to: "X_progress_visibility",
        cpd: { direction: "increase", strength: "strong" },
      },
      {
        id: "r_review_delay",
        type: "inference",
        scheme: "RESOLVES",
        from: "X_weekly_review",
        to: "X_intervention_delay",
        cpd: { direction: "decrease", strength: "moderate" },
      },
      {
        id: "r_review_evidence",
        type: "emission",
        scheme: "MANIFESTS_AS",
        from: "X_weekly_review",
        to: "O_gap_closed",
        cpd: {
          "fit->observed": 0.75,
          "unfit->observed": 0.25,
        },
      },
      {
        id: "r_solution_goal",
        type: "preference",
        scheme: "PREFERS",
        from: "X_action_metrics",
        to: "X_stable_judgment",
        cpd: { direction: "increase", strength: "moderate" },
      },
    ],
  },
  events: [
    {
      id: "e1",
      seq: 1,
      time: { abs: "2026-05-29T09:00:00" },
      type: "situated",
      variable: "S_growth",
      value: "true",
      evidence_state: "agreed",
    },
    {
      id: "e2",
      seq: 2,
      time: { abs: "2026-05-29T09:01:00" },
      type: "situated",
      variable: "S_distributed_managers",
      value: "true",
      evidence_state: "agreed",
    },
    {
      id: "e3",
      seq: 3,
      time: { abs: "2026-05-29T09:02:00" },
      type: "observed",
      variable: "O_manager_variance",
      value: "observed",
      evidence_state: "agreed",
    },
    {
      id: "e4",
      seq: 4,
      time: { abs: "2026-05-29T09:03:00" },
      type: "believed",
      variable: "X_progress_visibility",
      posterior: { absent: 0.76, present: 0.24 },
      evidence_state: "agreed",
    },
    {
      id: "e5",
      seq: 5,
      time: { abs: "2026-05-29T09:04:00" },
      type: "believed",
      variable: "X_intervention_delay",
      posterior: { present: 0.69, absent: 0.31 },
      evidence_state: "mentioned",
    },
    {
      id: "e6",
      seq: 6,
      time: { abs: "2026-05-29T09:05:00" },
      type: "believed",
      variable: "X_action_metrics",
      posterior: { fit: 0.81, unfit: 0.19 },
      evidence_state: "agreed",
    },
    {
      id: "e7",
      seq: 7,
      time: { abs: "2026-05-29T09:06:00" },
      type: "argued",
      relation_id: "r_metrics_visibility",
      evidence_state: "agreed",
    },
    {
      id: "e8",
      seq: 8,
      time: { abs: "2026-05-29T09:07:00" },
      type: "argued",
      relation_id: "r_review_delay",
      evidence_state: "mentioned",
    },
  ],
};

export const objectionSdDbnDocument = {
  "@type": "SD-DBN",
  version: "3.0",
  id: "doc-objection-evaluation-001",
  subject: "objection-evaluation",
  schema: {
    variables: [
      {
        id: "S_procurement",
        kind: "situation",
        domain: ["false", "true"],
        text: "Procurement approval is required",
      },
      {
        id: "X_security_concern",
        kind: "latent",
        role: "obstacle",
        domain: ["absent", "present"],
        desired_values: ["absent"],
        undesired_values: ["present"],
        text: "Security concern blocks adoption",
      },
      {
        id: "X_audit_pack",
        kind: "latent",
        role: "means",
        domain: ["unfit", "fit"],
        desired_values: ["fit"],
        undesired_values: ["unfit"],
        text: "Audit pack answers review",
      },
      {
        id: "X_owner_alignment",
        kind: "latent",
        role: "factor",
        domain: ["absent", "present"],
        desired_values: ["present"],
        undesired_values: ["absent"],
        text: "System owner is aligned",
      },
      {
        id: "X_purchase_ready",
        kind: "latent",
        role: "goal",
        domain: ["unmet", "met"],
        desired_values: ["met"],
        undesired_values: ["unmet"],
        text: "Purchase can proceed",
      },
      {
        id: "O_security_question",
        kind: "observation",
        domain: ["unobserved", "observed"],
        text: "Customer asks about data handling",
      },
      {
        id: "O_owner_quote",
        kind: "observation",
        domain: ["unobserved", "observed"],
        text: "Owner confirms review path",
      },
    ],
    relations: [
      {
        id: "r_procurement_security",
        type: "conditioning",
        scheme: "CONDITIONS",
        from: "S_procurement",
        to: "X_security_concern",
        cpd: { direction: "increase", strength: "moderate" },
      },
      {
        id: "r_security_question",
        type: "emission",
        scheme: "MANIFESTS_AS",
        from: "X_security_concern",
        to: "O_security_question",
        cpd: {
          "present->observed": 0.85,
          "absent->observed": 0.15,
        },
      },
      {
        id: "r_audit_security",
        type: "inference",
        scheme: "RESOLVES",
        from: "X_audit_pack",
        to: "X_security_concern",
        cpd: { direction: "decrease", strength: "strong" },
      },
      {
        id: "r_owner_quote",
        type: "emission",
        scheme: "MANIFESTS_AS",
        from: "X_owner_alignment",
        to: "O_owner_quote",
        cpd: {
          "present->observed": 0.78,
          "absent->observed": 0.22,
        },
      },
      {
        id: "r_owner_goal",
        type: "inference",
        scheme: "CAUSES",
        from: "X_owner_alignment",
        to: "X_purchase_ready",
        cpd: { direction: "increase", strength: "moderate" },
      },
    ],
  },
  events: [
    {
      id: "e1",
      seq: 1,
      time: { abs: "2026-05-29T10:00:00" },
      type: "situated",
      variable: "S_procurement",
      value: "true",
      evidence_state: "agreed",
    },
    {
      id: "e2",
      seq: 2,
      time: { abs: "2026-05-29T10:01:00" },
      type: "observed",
      variable: "O_security_question",
      value: "observed",
      evidence_state: "agreed",
    },
    {
      id: "e3",
      seq: 3,
      time: { abs: "2026-05-29T10:02:00" },
      type: "believed",
      variable: "X_security_concern",
      posterior: { present: 0.82, absent: 0.18 },
      evidence_state: "rejected",
    },
    {
      id: "e4",
      seq: 4,
      time: { abs: "2026-05-29T10:03:00" },
      type: "believed",
      variable: "X_audit_pack",
      posterior: { fit: 0.58, unfit: 0.42 },
      evidence_state: "mentioned",
    },
    {
      id: "e5",
      seq: 5,
      time: { abs: "2026-05-29T10:04:00" },
      type: "argued",
      relation_id: "r_audit_security",
      evidence_state: "rejected",
      attack_type: "undercut",
    },
    {
      id: "e6",
      seq: 6,
      time: { abs: "2026-05-29T10:05:00" },
      type: "believed",
      variable: "X_owner_alignment",
      posterior: { present: 0.64, absent: 0.36 },
      evidence_state: "mentioned",
    },
    {
      id: "e7",
      seq: 7,
      time: { abs: "2026-05-29T10:06:00" },
      type: "observed",
      variable: "O_owner_quote",
      value: "observed",
      evidence_state: "mentioned",
    },
  ],
};

export const formatSampleDocuments = [
  minimalSdDbnDocument,
  onboardingSdDbnDocument,
  objectionSdDbnDocument,
];
